### ISSUE TITLE
BMM Uploader - Not showing unpublished Fra Kåre tracks

### ISSUE THREAD

**Issue by ice1e0** [bcc-code/bcc-media-tools#19]
I tried to upload files but it is only showing Fra Kåre tracks up to today (20.08.). When I want to upload, I want most likely to upload to tracks which are yet unpublished ;-)

![image](https://github.com/user-attachments/assets/34257fc4-cf0d-4dea-ab40-44695678a852)

In the old BMM Admin area I already created the tracks until the end of the week (23.08.). The tracks for 21.08.-23.08. are not showing in the uploader app:

![image](https://github.com/user-attachments/assets/21b463b1-7b90-40a2-94c8-bdc31d8509dc)

**Comment by KillerX** [comment]
@kkuepper are you able to check this. It's most likely that the API is not returning the data, as there are no filters on this that I know on the backend.

**Comment by kkuepper** [comment]
https://github.com/bcc-code/bcc-media-tools/pull/20

I'm a bit flustered that we didn't notice it during our tests.

**Comment by KillerX** [comment]
<img width="351" alt="image" src="https://github.com/user-attachments/assets/547af049-bbb4-409d-b0f8-41cc24c90ea3">
Fix deployed
