### ISSUE TITLE
BMM Uploader - First upload test, test feedback

### ISSUE THREAD

**Issue by ice1e0** [bcc-code/bcc-media-tools#21]
I created now all tracks for the next week 35 from Fra Kåre in the BMM backend and uploaded only norwegian.

Then I logged in to the BMM Upload tool and uploaded the translation for english. Here the user flow:

## Selecting podcast + track + setting language 

![image](https://github.com/user-attachments/assets/298a09d1-44d6-4e85-8980-2acfed35a0c7)

![image](https://github.com/user-attachments/assets/87dddf66-99ad-4143-ad4a-a59aa4558069)

## Selecting file to upload

![image](https://github.com/user-attachments/assets/cb4d6f5e-e862-4701-8f3a-7b1930d352a7)

## Upload in progress

![image](https://github.com/user-attachments/assets/4b2a8bf1-89d1-446c-b740-07af446571a0)

## upload finished

![image](https://github.com/user-attachments/assets/95ff96fd-7a77-46c6-9e9b-a97a2eba0c51)

## Result in the BMM Backend

It took some minutes for the uploaded file to show in the BMM backend but now its there:

![image](https://github.com/user-attachments/assets/c01720cc-07d8-4796-8e6c-65c5d1b7ebd8)

The newly uploaded files get uploaded 3 times, twice in format aac:

![image](https://github.com/user-attachments/assets/85898a0a-250b-4b71-949b-68ed59a3afef)

My upload to Norwegian was only showing once as mpeg:

![image](https://github.com/user-attachments/assets/e665c342-2f7d-4312-abaa-a5ca0220d0f8)

Here are some points from my side:

- [x] Question: Could the selection page (first screenshot) be build that people know what podcast they're uploading for? e.g. showing "Fra Kåre" somewhere?
- [x] Question: Could the UI build in a way to show which tracks are not translated yet in a specific language? e.g. when I select "German", those are showing red when the translation is not yet uploaded.
- [x] Bug: The text is not synchronized to BMM backend. Looks like this does not work.
- [x] Question: Is it intended that the files are unpublished? If yes, who should by design be in charge to do the publishing of a translation?
- [x] Question: Are the 2x uploads with acc format intended? 
- [ ] Suggestion: There is currently no option to correct my translation of the track when I messed up the text, according to the note message. I would suggest to add this in the future.

**Comment by kkuepper** [comment]
- The acc format is intended. We want to use that to offer a lower quality version (Especially Africa is interested in that)
- The upload form doesn't affect the published status of the language. The reason that it's unpublished, is because when the track is created it adds all languages of the parent album as unpublished. As a workaround you could delete all languages but norwegian, before uploading using [tools.bcc.media](https://tools.bcc.media/). When mediabanken sends the files to BMM, it will create the missing translation and sets it to published.

**Comment by ice1e0** [comment]
@kkuepper OK. Today I uploaded it normally, but for tomorrow I now removed all languages which are not yet uploaded.
In the Fra Kåre overview I see now some languages as required, but not all:
![image](https://github.com/user-attachments/assets/f29b45a3-a4df-45da-b2fc-8643524a3e3f)

Shall we extend this to the languages which usually are uploaded day by day? When I remove it, we don't have an overview anymore for the other languages which did not uploaded their translation yet.

**Comment by KillerX** [comment]
> Bug: The text is not synchronized to BMM backend. Looks like this does not work.

For now we will disable the title function, and potentially bring it back later when we have a better understanding of the usage.

**Comment by KillerX** [comment]
> It look now 11 minutes 45 seconds until a uploaded file was visible in the BMM Backend as uploaded. I would suggest an improvement of the processing speed.

Due to the processes that happen now (import, transcription, and transcoding) it is unlikely that we can reduce the time in a major way. 
We are open for ideas about what we can do to reduce the impact of this. Some suggestions:

* Email to uploader
* Telegram message to a Chanel/Group
* Screenshot of the "podcast status page"

Note: We hope that in the future the translators will be able to upload themselves and only the final control needs to be performed in BMM admin.

**Comment by kkuepper** [comment]
@ice1e0 You can also just hit publish before uploading the file. If there is a published language, with a title but no file, it will be treated as unpublished.

**Comment by ice1e0** [comment]
I did this now for all translations, but now the uploader does not show the new files, so I started again to upload all files for tomorrow with the old backend. 

All uploads I did with the new upload tool showed that the upload worked, but I have no insight what happens after that. Maybe the background jobs crashed? Maybe soneone can check this @KillerX @kkuepper

**Comment by KillerX** [comment]
> I did this now for all translations, but now the uploader does not show the new files, so I started again to upload all files for tomorrow with the old backend.
> 
> All uploads I did with the new upload tool showed that the upload worked, but I have no insight what happens after that. Maybe the background jobs crashed? Maybe soneone can check this @KillerX @kkuepper

This is fixed now, I introduced a deadlock for "large" files on the transcription step. (https://github.com/bcc-code/ai-api/commit/e242a359699778632edee8695cecefdc2236313e#diff-ea32506df4e1e5db9fc091b05eeb2fc675d37d339985eefbfc90b7b5a8308a29L174). I agree that we sould add more visibility into the process, but in this case it would have been really hard to do something because nothing failed, it was actually a deadlock (https://github.com/golang/go/issues/16787).

**Comment by kkuepper** [comment]
An idea to automate catching errors like that: send an alert if it's been more than 24h that a file has been successfully processed. Though it might give false positives at a time when no files are processed (e.g. Christmas).

**Comment by ice1e0** [comment]
@kkuepper I would rather suggest to create a logging for the job process - either in a database or in a logging file - and interpret this with a reporting tool. E.g. using structured logging and save per job start/stop information in the log a unique UUID for each job run. Then it should be possible to add this into monitoring of the BMM environment ...

**Comment by KillerX** [comment]
I think the correct thing is to reduce the timeout on those jobs to something less than 1 week :)
Given that our recordings are generally not > 5h, a 6h deadline on a transcription job should be more than enough from the time it is in progress. (and maybe 24, from when it was queued).

**Comment by KillerX** [comment]
@kkuepper ref:

>  Question: Could the UI build in a way to show which tracks are not translated yet in a specific language? e.g. when I select "German", those are showing red when the translation is not yet uploaded.

Currently the API just returns a list of the "active" languages, but I don't see any information about the published state, so I don't believe I am able to do this from the data we are currently getting.

**Comment by kkuepper** [comment]
If you add ?raw=true, you get the track as it's stored in the database and not as a simplified structure. Then you can see which languages are published.

**Comment by KillerX** [comment]
@ice1e0 can you take a look at #26 and comment if that makes sense from your POV?

**Comment by ice1e0** [comment]
@KillerX yes it make sense but does not work with each browser. Most likely because of the emoji implementation. See the comment in the PR

**Comment by KillerX** [comment]
Fixed

**Comment by KillerX** [comment]
I'll close this issue, as I think we have addressed most of the things. Let's open new issues for more/other/new things.
