### ISSUE TITLE
Language selector in download page is empty, dropdown shows JSON data

### ISSUE THREAD

**Issue by ice1e0** [bcc-code/bcc-media-tools#30]
Language selector in download page is empty, dropdown shows JSON data

![image](https://github.com/user-attachments/assets/48cdb2c8-ae35-4849-b793-115ad3a373a0)

**Comment by ice1e0** [comment]
Additional point: Now this is corrected that it shows the language code. 

![image](https://github.com/user-attachments/assets/7dc43668-1382-4509-b648-0c9b30d78df7)

But the UX feeling is a bit odd because in the page before the dropdown shows the full name in english:

![image](https://github.com/user-attachments/assets/450ac687-a10a-4e9a-8caa-6b71af8d4b34)

**Comment by sifferhans** [comment]
@ice1e0 Could you test this again now?

**Comment by ice1e0** [comment]
@sifferhans Looks good now!
