### ISSUE TITLE
Sort the flags

### ISSUE THREAD

**Issue by ice1e0** [bcc-code/bcc-media-tools#31]
Is it possible to sort the flags so that the languages show always in the same order when every language is uploaded?

![image](https://github.com/user-attachments/assets/b2b8df2c-ed9a-43af-98ee-d699df200f62)

Its a bit confusing to look at the flags in different order. E.g. the dutch/netherlands flag is after the romanian for the 16th, but for the 13th it is before it. This makes it hard to find out which language is missing when comparing it to the previous days.

**Comment by KillerX** [comment]
![367621693-b2b8df2c-ed9a-43af-98ee-d699df200f62](https://github.com/user-attachments/assets/ed40a205-c862-4c7b-b2ae-96be32749c1c)

The flags are sorted. Pretty sure you mixed RU and NL.
But I agree that we should try to somehow improve that. Maybe always show all languages but fade/gray out the missing ones? If we then split the title and the flags in 2 rows, it should be reasonably easy to compare...

**Comment by KillerX** [comment]
Of course another option would be to ask RU to change their flag to something more distinct XD

**Comment by sifferhans** [comment]
@ice1e0 @KillerX We could also make the flags always stay in the same column, and have empty spaces where there are no flags. This way they would always be the same spot:

![CleanShot 2024-09-19 at 10 46 35](https://github.com/user-attachments/assets/9cbc0124-365f-4271-84eb-998d5dc8d6fc)

**Comment by KillerX** [comment]
That was sort of my idea, but if we show the missing flags "weakly" then it's even easier to identify what you are missing. Otherwise you just see "something" missing but you do not know what.

**Comment by sifferhans** [comment]
Fixed by https://github.com/bcc-code/bcc-media-tools/pull/44

**Comment by sifferhans** [comment]
@ice1e0 Can you take a look at the upload form now and see if it is any better?

**Comment by sifferhans** [comment]
@ice1e0 How about now?

**Comment by ice1e0** [comment]
@sifferhans Yes 👏 now it works fine
