### ISSUE TITLE
UX/CSS bug language text on upload side

### ISSUE THREAD

**Issue by ice1e0** [bcc-code/bcc-media-tools#34]
UX/CSS bug language text on upload side: When the lanugage name is too long it gets overwridden with the drop down arrow

![image](https://github.com/user-attachments/assets/2881fc42-8f4d-4247-aa54-56edba9a704c)

**Comment by sifferhans** [comment]
https://github.com/bcc-code/bcc-media-tools/pull/44

**Comment by sifferhans** [comment]
@ice1e0 Can you take a look and confirm if it is fixed for you?

**Comment by ice1e0** [comment]
Yes 👏  this looks good now!
