### ISSUE TITLE
Unstable when uploading audio files to BMM/Fra Kåre

### ISSUE THREAD

**Issue by ice1e0** [bcc-code/bcc-media-tools#39]
It looks like that the upload tool is a bit unstable: The following tracks have been uploaded today and are not seen as finished after 30 minutes. We uploaded them again - but it just shows that the uploading somehow broke in the background:

German: FRAK_20240926_MAS_DE.mp3
Dutch: FRAK_20240926_KJS_MAS_NL.mp3
Estonian: FRAK_202409026_EST.mp3
Khasi: FRAK_20240926_MAS_KHA.mp3

I guess it is again the transcription AI which didn't work, so it doesn't get saved. I think there should be some "save commit" in between so that at least the upload and convertion of the audio files is saved. I am afraid that otherwise this will cause that people will not get Fra Kåre in the morning, because the uploader user does not check if the upload has worked or not 10-15 minutes after uploading the audio file. I think this is a mission critical bug.

**Comment by ice1e0** [comment]
Today I started uploading all languages between 22:45 and 23:13, but many where not uploaded.

The following files have been uploaded but are not visible in the daily upload:

FRAK_20241002_MAS_HUN.mp3
FRAK_20241002_MAS_RUS.mp3
FRAK_20241002_MAS_SPA.mp3
FRAK_20241002_MAS_SLO.mp3
(the other languages shown with X are not yet created)

![image](https://github.com/user-attachments/assets/fdf2f0ed-4b01-4a10-a0ce-963698945ff3)

I will now try upload them again.

**Comment by ice1e0** [comment]
Today I uploaded spanish a few minutes after 20:39 o'clock CET but it was not processed. I uploaded it then again and according to the "BCCM - BMM Exports" telegram channel it was processed the secound time at 21:04-21:07 o'clock.

It looked like that around that time the API was offline, because the refresh sign was running and never ending on the BMM Upload page:
![image](https://github.com/user-attachments/assets/69ad4135-a4e0-476a-ac33-a64b9ac0cd38)
I tried several times to refresh it. The website was quick and responsive e.g. in the main menu, but this page was still running a never ending refresh sign. Could be that there was an update to the API tonight which caused this? @kkuepper

**Comment by kkuepper** [comment]
Hm. The idea of the deployment sounds plausible.
But the deployment should actually happen without downtime. Though it might still be affected for 30s.
Also when looking closer at Monday's deployments, there was only one deployment an hour later at 9:49.

**Comment by kkuepper** [comment]
After more investigation it shows that no files were received through the upload form between 20:30 and 20:51.
So it seems that the upload form failed and didn't inform you about that it failed. So we should make sure that it doesn't fail silently.

<img width="510" alt="Screenshot 2024-10-29 at 8 52 35 AM" src="https://github.com/user-attachments/assets/9b554936-6f15-477a-b542-2a68d979778b">

**Comment by ice1e0** [comment]
Right. Maybe a double handshake shoehorn before „upload finished“ is shown

**Comment by KillerX** [comment]
I am now making sure that if the backend returns an error an alert is produced (and added some more server side logs as well)
