### ISSUE TITLE
sync-fix tools didnt fix VX-483647

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-tools#5]
Applied time adjustment twice on VX-483647

Once for reaper vs youplay delay (-159ms) and once for youplay video vs audio delay (-440ms)

Got notification the adjustments has been applied but when exporting to vod with related audio, the audio is still out of sync, same as before the adjustment

**Comment by mulundapm** [comment]
VX-486456 has to be adjusted by -596ms

tried sync tool and failed

**Comment by KillerX** [comment]
This tool only supports Reaper VS YouPlay

**Comment by KillerX** [comment]
(Note: The stated VX id no longer exists in MB as it was purged).

**Comment by kkuepper** [comment]
@mulundapm I think you assigned this to me by accident.
