### ISSUE TITLE
Add transcription access to BMM Upload Form

### ISSUE THREAD

**Issue by KillerX** [bcc-code/bcc-media-tools#59]
- [x] Add API call to get transcription for a specific language
- [x] Show transcription in upload form
- [x] Make it possible to change transcription language (mainly EN, NO) (don't create the expectation that NO is available if only et has been uploaded)

**Comment by KillerX** [comment]
@sifferhans: PR for backend https://github.com/bcc-code/bcc-media-tools/pull/64

**Comment by sifferhans** [comment]
@KillerX What and where exactly should the transcriptions be visible? What function does it have?

**Comment by KillerX** [comment]
If I understand the situation correctly the purpose is to expose them for the users of the upload form so they can use them as a base for translation, but I don't have any concrete ideas as to where/how in the UI they should show up.
I do recall that @kkuepper had some thoughts on that.

**Comment by sifferhans** [comment]
Ok, then I will wait with this until Karsten can answer
